### PR TITLE
Add pybind11 type_caster to header file torch/csrc/utils/pybind.h

### PR DESCRIPTION
**Pull request by houseroad**
#154 We can put the type_caster into header file torch/csrc/utils/pybind.h.

### CODE REVIEW

**Comment by apaszke** [comment]
I'm a bit concerned about this solution, because it's going to add fake header dependencies (everything is imported in `pybind.h` and everything will import `pybind.h`). That's why I thought about adding separate `pybind.h` files in each directory under `torch/csrc/`, and only including them accross directories when they are really needed. @zdevito @ezyang any opinions?

**Comment by ezyang** [comment]
Only Python cpp files are going to import pybind.h, right? That doesn't seem terrible to me.

I agree a reasonable alternative is to have a separate pybind file per file, but that just sounds annoying.

**Comment by houseroad** [comment]
I will try to extract the implementation from the header file, put it into a cpp file, and keep minimal imports in the header file. Does this sound like a reasonable solution? @apaszke @ezyang

**Comment by houseroad** [comment]
Due to the macro in the pybind11, the class forwarding won't work. So I will split it into different header files.

**Pull request merged**
